///////////////////////////////////////////////////////////
//  FieldTypeIso8583.cs
//  Implementation of the Enumeration FieldTypeIso8583
//  Generated by Enterprise Architect
//  Created on:      12-dic.-2017 06:17:16 p. m.
//  Original author: Javier de J. Flores Mondragón
///////////////////////////////////////////////////////////

namespace InnSyTech.Standard.Net.Communication.Iso8583
{
    /// <summary>
    /// Representa los tipos de campos disponibles para el envío de mensajes a través del ISO 8583.
    /// </summary>
    public enum FieldTypeIso8583 : int
    {
        /// <summary>
        /// Campo tipo númerico.
        /// </summary>
        Numeric = 1,

        /// <summary>
        /// Campo tipo alfanumérico.
        /// </summary>
        Alphanumeric = 2,

        /// <summary>
        /// Campo tipo caracteres especiales.
        /// </summary>
        Special = 4,

        /// <summary>
        /// Campo tipo binario.
        /// </summary>
        Binary = 8,

        /// <summary>
        /// Campo con longitud variable [1..9] digitos o caracteres.
        /// </summary>
        Lvar = 16,

        /// <summary>
        /// Campo con longitud variable [1..99] digitos o caracteres.
        /// </summary>
        Llvar = 32,

        /// <summary>
        /// Campo con longitud variable [1..999] digitos o caracteres.
        /// </summary>
        Lllvar = 64,

        /// <summary>
        /// Campo con formato hexadecimal.
        /// </summary>
        Hexadecimal = 128,

        /// <summary>
        /// Campo con formato decimal codificado en binario.
        /// </summary>
        BinaryCodedDecimal = 256
    }
}