SELECT (SELECT NO_ECON FROM SITM_DISP.SFVH_VEHI),
    CASE 
        WHEN ACCE_SALI.FECH IS NOT NULL THEN ACCE_SALI.FECH
        WHEN CONT_ACCE.FECH IS NOT NULL THEN CONT_ACCE.FECH
        WHEN TURN.FECH IS NOT NULL THEN TURN.FECH
        WHEN ASGN_TURN.FECH IS NOT NULL THEN ASGN_TURN.FECH
        WHEN ASGN_RUTA.FECH IS NOT NULL THEN ASGN_RUTA.FECH
        WHEN RECE_NAVE.FECH IS NOT NULL THEN RECE_NAVE.FECH
        ELSE NULL
    END FECHA,
    SUM(CASE WHEN VAL_DISP IS NULL THEN 0 ELSE VAL_DISP END) VAL_DISP, 
    SUM(CASE WHEN VAL_ENVI IS NULL THEN 0 ELSE VAL_ENVI END) VAL_ENVI, 
    SUM(CASE WHEN VAL_ENV_PEN IS NULL THEN 0 ELSE VAL_ENV_PEN END) VAL_ENV_PEN,
    SUM(CASE WHEN CONT_DISP IS NULL THEN 0 ELSE CONT_DISP END) CONT_DISP, 
    SUM(CASE WHEN CONT_ENVI IS NULL THEN 0 ELSE CONT_ENVI END) CONT_ENVI, 
    SUM(CASE WHEN CONT_ENV_PEN IS NULL THEN 0 ELSE CONT_ENV_PEN END) CONT_ENV_PEN,
    SUM(CASE WHEN TURN_DISP IS NULL THEN 0 ELSE TURN_DISP END) TURN_DISP, 
    SUM(CASE WHEN TURN_ENVI IS NULL THEN 0 ELSE TURN_ENVI END) TURN_ENVI, 
    SUM(CASE WHEN TURN_ENV_PEN IS NULL THEN 0 ELSE TURN_ENV_PEN END) TURN_ENV_PEN,    
    SUM(CASE WHEN ASGN_TURN_DISP IS NULL THEN 0 ELSE ASGN_TURN_DISP END) ASGN_TURN_DISP, 
    SUM(CASE WHEN ASGN_TURN_ENVI IS NULL THEN 0 ELSE ASGN_TURN_ENVI END) ASGN_TURN_ENVI, 
    SUM(CASE WHEN ASGN_TURN_ENV_PEN IS NULL THEN 0 ELSE ASGN_TURN_ENV_PEN END) ASGN_TURN_ENV_PEN,    
    SUM(CASE WHEN ASGN_RUTA_DISP IS NULL THEN 0 ELSE ASGN_RUTA_DISP END) ASGN_RUTA_DISP, 
    SUM(CASE WHEN ASGN_RUTA_ENVI IS NULL THEN 0 ELSE ASGN_RUTA_ENVI END) ASGN_RUTA_ENVI, 
    SUM(CASE WHEN ASGN_RUTA_ENV_PEN IS NULL THEN 0 ELSE ASGN_RUTA_ENV_PEN END) ASGN_RUTA_ENV_PEN,    
    SUM(CASE WHEN RECE_NAVE_DISP IS NULL THEN 0 ELSE RECE_NAVE_DISP END) RECE_NAVE_DISP, 
    SUM(CASE WHEN RECE_NAVE_ENVI IS NULL THEN 0 ELSE RECE_NAVE_ENVI END) RECE_NAVE_ENVI, 
    SUM(CASE WHEN RECE_NAVE_ENV_PEN IS NULL THEN 0 ELSE RECE_NAVE_ENV_PEN END) RECE_NAVE_ENV_PEN 
FROM (
SELECT DISP.FECHA FECH, SUM(VAL_DISP) VAL_DISP, SUM(VAL_ENVI) VAL_ENVI, SUM(VAL_ENV_PEN) VAL_ENV_PEN 
FROM (
	SELECT DATE(FCH_ACCE_SALI) FECHA, COUNT(*) VAL_DISP FROM SITM_DISP.SBOP_ACCE_SALI GROUP BY FECHA
) DISP LEFT JOIN (
	SELECT DATE(FCH_ENVI) FECHA, COUNT(*) VAL_ENVI FROM SITM_ENVI.SBOP_ACCE_SALI GROUP BY FECHA
) ENVI ON DISP.FECHA=ENVI.FECHA LEFT JOIN (
	SELECT DATE(FCH_ENVI) FECHA, COUNT(*) VAL_ENV_PEN FROM SITM_ENVI.SBOP_ACCE_SALI WHERE BOL_ENVI=FALSE GROUP BY FECHA
) ENV_PEN ON ENVI.FECHA=ENV_PEN.FECHA
GROUP BY FECH) ACCE_SALI FULL OUTER JOIN  (
SELECT DISP.FECHA FECH, SUM(CONT_DISP) CONT_DISP, SUM(CONT_ENVI) CONT_ENVI, 
    SUM(CONT_ENV_PEN) CONT_ENV_PEN 
FROM (
	SELECT DATE(FCH_CONT_ACCE) FECHA, COUNT(*) CONT_DISP FROM SITM_DISP.SBOP_CONT_ACCE GROUP BY FECHA
) DISP LEFT JOIN (
	SELECT DATE(FCH_ENVI) FECHA, COUNT(*) CONT_ENVI FROM SITM_ENVI.SBOP_CONT_ACCE GROUP BY FECHA
) ENVI ON DISP.FECHA=ENVI.FECHA LEFT JOIN (
	SELECT DATE(FCH_ENVI) FECHA, COUNT(*) CONT_ENV_PEN FROM SITM_ENVI.SBOP_CONT_ACCE WHERE BOL_ENVI=FALSE GROUP BY FECHA
) ENV_PEN ON ENVI.FECHA=ENV_PEN.FECHA
GROUP BY FECH) CONT_ACCE ON ACCE_SALI.FECH=CONT_ACCE.FECH FULL OUTER JOIN  (
SELECT DISP.FECHA FECH, SUM(TURN_DISP) TURN_DISP, SUM(TURN_ENVI) TURN_ENVI, 
    SUM(TURN_ENV_PEN) TURN_ENV_PEN 
FROM (
	SELECT DATE(FCH_CREA) FECHA, COUNT(*) TURN_DISP FROM SITM_DISP.SBOP_TURN GROUP BY FECHA
) DISP LEFT JOIN (
	SELECT DATE(FCH_ENVI) FECHA, COUNT(*) TURN_ENVI FROM SITM_ENVI.SBOP_TURN GROUP BY FECHA
) ENVI ON DISP.FECHA=ENVI.FECHA LEFT JOIN (
	SELECT DATE(FCH_ENVI) FECHA, COUNT(*) TURN_ENV_PEN FROM SITM_ENVI.SBOP_TURN WHERE BOL_ENVI=FALSE GROUP BY FECHA
) ENV_PEN ON ENVI.FECHA=ENV_PEN.FECHA
GROUP BY FECH) TURN ON ACCE_SALI.FECH=TURN.FECH FULL OUTER JOIN  (
SELECT DISP.FECHA FECH, SUM(ASGN_TURN_DISP) ASGN_TURN_DISP, SUM(ASGN_TURN_ENVI) ASGN_TURN_ENVI, 
    SUM(ASGN_TURN_ENV_PEN) ASGN_TURN_ENV_PEN 
FROM (
	SELECT DATE(FCH_CREA) FECHA, COUNT(*) ASGN_TURN_DISP FROM SITM_DISP.SBOP_ASGN_TURN GROUP BY FECHA
) DISP LEFT JOIN (
	SELECT DATE(FCH_ENVI) FECHA, COUNT(*) ASGN_TURN_ENVI FROM SITM_ENVI.SBOP_ASGN_TURN GROUP BY FECHA
) ENVI ON DISP.FECHA=ENVI.FECHA LEFT JOIN (
	SELECT DATE(FCH_ENVI) FECHA, COUNT(*) ASGN_TURN_ENV_PEN FROM SITM_ENVI.SBOP_ASGN_TURN WHERE BOL_ENVI=FALSE GROUP BY FECHA
) ENV_PEN ON ENVI.FECHA=ENV_PEN.FECHA
GROUP BY FECH) ASGN_TURN ON ACCE_SALI.FECH=ASGN_TURN.FECH FULL OUTER JOIN  (
SELECT DISP.FECHA FECH, SUM(ASGN_RUTA_DISP) ASGN_RUTA_DISP, SUM(ASGN_RUTA_ENVI) ASGN_RUTA_ENVI, 
	SUM(CASE WHEN ASGN_RUTA_ENV_PEN IS NULL THEN 0 ELSE ASGN_RUTA_ENV_PEN END) ASGN_RUTA_ENV_PEN 
FROM (
	SELECT DATE(FCH_CREA) FECHA, COUNT(*) ASGN_RUTA_DISP FROM SITM_DISP.SFRU_ASGN GROUP BY FECHA
) DISP LEFT JOIN (
	SELECT DATE(FCH_ENVI) FECHA, COUNT(*) ASGN_RUTA_ENVI FROM SITM_ENVI.SFRU_ASGN GROUP BY FECHA
) ENVI ON DISP.FECHA=ENVI.FECHA LEFT JOIN (
	SELECT DATE(FCH_ENVI) FECHA, COUNT(*) ASGN_RUTA_ENV_PEN FROM SITM_ENVI.SFRU_ASGN WHERE BOL_ENVI=FALSE GROUP BY FECHA
) ENV_PEN ON ENVI.FECHA=ENV_PEN.FECHA
GROUP BY FECH) ASGN_RUTA ON ACCE_SALI.FECH=ASGN_RUTA.FECH FULL OUTER JOIN  (
SELECT DISP.FECHA FECH, SUM(RECE_NAVE_DISP) RECE_NAVE_DISP, SUM(RECE_NAVE_ENVI) RECE_NAVE_ENVI, 
	SUM(CASE WHEN RECE_NAVE_ENV_PEN IS NULL THEN 0 ELSE RECE_NAVE_ENV_PEN END) RECE_NAVE_ENV_PEN 
FROM (
	SELECT DATE(FCH_CREA) FECHA, COUNT(*) RECE_NAVE_DISP FROM SITM_DISP.SFMO_HIST_RECE_NAVE GROUP BY FECHA
) DISP LEFT JOIN (
	SELECT DATE(FCH_ENVI) FECHA, COUNT(*) RECE_NAVE_ENVI FROM SITM_ENVI.SFMO_HIST_RECE_NAVE GROUP BY FECHA
) ENVI ON DISP.FECHA=ENVI.FECHA LEFT JOIN (
	SELECT DATE(FCH_ENVI) FECHA, COUNT(*) RECE_NAVE_ENV_PEN FROM SITM_ENVI.SFMO_HIST_RECE_NAVE WHERE BOL_ENVI=FALSE GROUP BY FECHA
) ENV_PEN ON ENVI.FECHA=ENV_PEN.FECHA
GROUP BY FECH) RECE_NAVE ON ACCE_SALI.FECH=RECE_NAVE.FECH
GROUP BY FECHA ORDER BY FECHA