SELECT FECHA, 
	SUM(CASE WHEN  COSTO=0 THEN VALIDACIONES ELSE 0 END) MONEDERO_COSTO_0,
	SUM(CASE WHEN COSTO=3 THEN VALIDACIONES ELSE 0 END) MONEDERO_COSTO_3,
	SUM(CASE WHEN  COSTO=10 THEN VALIDACIONES ELSE 0 END) MONEDERO_COSTO_10
FROM (
SELECT
DATE(FCH_ACCE_SALI) AS FECHA,
COST_VIAJ AS COSTO,
COUNT(ID_ACCE_SALI) AS VALIDACIONES,
SUM(COST_VIAJ) AS COSTOS
FROM SITM.SBOP_ACCE_SALI AS ACCE
LEFT JOIN SITM.SBEQ_EQUI AS EQUI ON ACCE.ID_EQUI = EQUI.ID_EQUI
LEFT JOIN SITM.CCTM_INV AS INV ON INV.ID_INV=EQUI.ID_INV
LEFT JOIN SITM.SBOP_ASGN_TURN AS ASGN ON ASGN.ID_TURN = ACCE.ID_TURN AND ASGN.ID_EQUI=ACCE.ID_EQUI
WHERE DATE(FCH_ACCE_SALI) BETWEEN DATE('{paramFchIni}') AND (DATE('{paramFchIni}') + 6)
AND ACCE.ID_TIPO_ACCE NOT IN (327,868) AND ASGN.ID_VEHI IS NULL AND INV.ID_PROD=56
GROUP BY FECHA, COSTO
ORDER BY FECHA ASC, COSTO ASC
)
GROUP BY FECHA
ORDER BY FECHA