SELECT FECHA, 
	SUM(CASE WHEN COSTO=0 THEN VALIDACIONES ELSE 0 END) MONEDERO_COSTO_0,
	SUM(CASE WHEN COSTO=3 THEN VALIDACIONES ELSE 0 END) MONEDERO_COSTO_3,
	SUM(CASE WHEN COSTO=7 THEN VALIDACIONES ELSE 0 END) MONEDERO_COSTO_7,
	SUM(CASE WHEN COSTO=10 THEN VALIDACIONES ELSE 0 END) MONEDERO_COSTO_10
FROM (
SELECT 
    DATE(FCH_ACCE_SALI) AS FECHA,
    COST_VIAJ AS COSTO, 
    COUNT(ID_ACCE_SALI) AS VALIDACIONES,
    SUM(COST_VIAJ) AS COSTOS
FROM SITM.SBOP_ACCE_SALI AS ACCE
JOIN SITM.SBEQ_EQUI AS EQUI ON ACCE.ID_EQUI = EQUI.ID_EQUI
JOIN SITM.CCTM_INV AS INV ON INV.ID_INV=EQUI.ID_INV
JOIN SITM.SBOP_ASGN_TURN AS ASGN ON ASGN.ID_TURN = ACCE.ID_TURN AND ASGN.ID_EQUI=ACCE.ID_EQUI
JOIN SITM.SFVH_VEHI AS VEHI ON VEHI.ID_VEHI = ASGN.ID_VEHI
JOIN SITM.SFVH_TIPO_VEHI AS TIPO_VEHI ON VEHI.ID_TIPO_VEHI = TIPO_VEHI.ID_TIPO_VEHI
WHERE DATE(FCH_ACCE_SALI) BETWEEN DATE('{paramFchIni}') AND (DATE('{paramFchIni}') + 6)
AND ACCE.ID_TIPO_ACCE NOT IN (327,868,902,904) AND INV.ID_PROD=56
GROUP BY FECHA, COSTO
)
GROUP BY FECHA
ORDER BY FECHA