SELECT FECHA, SUM(VALIDACIONES), SUM(COSTOS)
FROM (
SELECT 
    DATE(FCH_ACCE_SALI) AS FECHA,
    SCRE.DES_SCRE AS CREDENCIAL, 
    COST_VIAJ AS COSTO, 
    COUNT(ID_ACCE_SALI) AS VALIDACIONES,
    SUM(COST_VIAJ) AS COSTOS
FROM SITM.SBOP_ACCE_SALI AS ACCE
JOIN SITM.SBEQ_EQUI AS EQUI ON ACCE.ID_EQUI = EQUI.ID_EQUI
JOIN SITM.SFVH_VEHI AS VEHI ON VEHI.ID_VEHI = EQUI.ID_VEHI
JOIN SITM.COAC_SCRE AS SCRE ON UPPER(SCRE.COD_SCRE) = UPPER(ACCE.TCRE)
WHERE DATE(FCH_ACCE_SALI) BETWEEN DATE('{paramFchIni}') AND (DATE('{paramFchIni}') + 6)
AND ACCE.ID_TIPO_ACCE NOT IN (327,868,902,904)
AND SCRE.DES_SCRE LIKE 'MONEDERO%'
GROUP BY FECHA, CREDENCIAL, COSTO
UNION
SELECT
DATE(FCH_ACCE_SALI) AS FECHA, 
SCRE.DES_SCRE AS CREDENCIAL,
COST_VIAJ AS COSTO,
COUNT(ID_ACCE_SALI) AS VALIDACIONES,
SUM(COST_VIAJ) AS COSTOS
FROM SITM.SBOP_ACCE_SALI AS ACCE
JOIN SITM.SBEQ_EQUI AS EQUI ON ACCE.ID_EQUI = EQUI.ID_EQUI AND EQUI.ID_LIN_EST IS NOT NULL
JOIN SITM.COAC_SCRE AS SCRE ON UPPER(SCRE.COD_SCRE) = UPPER(ACCE.TCRE)
WHERE DATE(FCH_ACCE_SALI) BETWEEN DATE('{paramFchIni}') AND (DATE('{paramFchIni}') + 6)
AND ACCE.ID_TIPO_ACCE NOT IN (327,868)
AND SCRE.DES_SCRE LIKE 'MONEDERO%'
GROUP BY FECHA, CREDENCIAL, COSTO
UNION 
SELECT
DATE(FCH_ACCE_SALI) AS FECHA,
'MONEDERO' AS CREDENCIAL,
COST_VIAJ AS COSTO,
COUNT(ID_ACCE_SALI) AS VALIDACIONES,
SUM(COST_VIAJ) AS COSTOS
FROM SITM.SBOP_ACCE_SALI AS ACCE
LEFT JOIN SITM.SBEQ_EQUI AS EQUI ON ACCE.ID_EQUI = EQUI.ID_EQUI
LEFT JOIN SITM.CCTM_INV AS INV ON INV.ID_INV=EQUI.ID_INV
LEFT JOIN SITM.SBOP_ASGN_TURN AS ASGN ON ASGN.ID_TURN = ACCE.ID_TURN AND ASGN.ID_EQUI=ACCE.ID_EQUI
WHERE DATE(FCH_ACCE_SALI) BETWEEN  DATE('{paramFchIni}') AND (DATE('{paramFchIni}') + 6)
AND ACCE.ID_TIPO_ACCE NOT IN (327,868,902,904) AND INV.ID_PROD=56
GROUP BY FECHA, COSTO
ORDER BY FECHA ASC, CREDENCIAL ASC, COSTO ASC
)
GROUP BY FECHA
ORDER BY FECHA