SELECT FECHA, SUM(VALIDACIONES), SUM(COSTOS)
FROM (
SELECT
    DATE(FCH_ACCE_SALI) AS FECHA,
    VEHI.NO_ECON,
    TIPO_VEHI.MOD_COME AS TIPO_VEHICULO,
    COUNT(ID_ACCE_SALI) AS VALIDACIONES,
    SUM(sald_ini) AS COSTOS
FROM SITM.SBOP_ACCE_SALI AS ACCE
JOIN SITM.SBEQ_EQUI AS EQUI ON ACCE.ID_EQUI = EQUI.ID_EQUI
JOIN SITM.SFVH_VEHI AS VEHI ON VEHI.ID_VEHI = EQUI.ID_VEHI
JOIN SITM.SFVH_TIPO_VEHI AS TIPO_VEHI ON VEHI.ID_TIPO_VEHI = TIPO_VEHI.ID_TIPO_VEHI
JOIN SITM.COAC_SCRE AS SCRE ON UPPER(SCRE.COD_SCRE) = UPPER(ACCE.TCRE)
WHERE DATE(FCH_ACCE_SALI) BETWEEN DATE('{paramFchIni}') AND (DATE('{paramFchIni}') + 6)
AND ACCE.ID_TIPO_ACCE IN (902,904)
GROUP BY FECHA,VEHI.NO_ECON, TIPO_VEHICULO
)
GROUP BY FECHA
ORDER BY FECHA