SELECT FECHA,
	COUNT(CASE WHEN SALD_INI=0 AND COST_VIAJ=7 THEN SALD_TARJ END) VAL_CRED_7,
	SUM(CASE WHEN SALD_INI=0 AND COST_VIAJ=7 THEN SALD_TARJ END) COSTOS_CRED_7,
	COUNT(CASE WHEN SALD_INI=0 AND COST_VIAJ=10 THEN SALD_TARJ END) VAL_CRED_10,
	SUM(CASE WHEN SALD_INI=0 AND COST_VIAJ=10 THEN SALD_TARJ END) COSTOS_CRED_10,
	COUNT(CASE WHEN SALD_INI<>0 AND COST_VIAJ=10 THEN SALD_TARJ END) VAL_PAR_CRED_10,
	SUM(CASE WHEN SALD_INI<>0 AND COST_VIAJ=10 THEN SALD_TARJ END) COSTOS_PAR_CRED_10,
	COUNT(CASE WHEN SALD_INI<>0 AND COST_VIAJ=7 THEN SALD_TARJ END) VAL_PAR_CRED_7,
	SUM(CASE WHEN SALD_INI<>0 AND COST_VIAJ=7 THEN SALD_TARJ END) COSTOS_PAR_CRED_7,
	COUNT(CASE WHEN COST_VIAJ=3 THEN SALD_TARJ END) VAL_CRED_3,
	SUM(CASE WHEN COST_VIAJ=3 THEN SALD_TARJ END) COSTOS_CRED_3
FROM (
SELECT
    DATE(FCH_ACCE_SALI) AS FECHA,
    SALD_INI,
    COST_VIAJ,
    SALD_TARJ*-1 AS SALD_TARJ
FROM SITM.SBOP_ACCE_SALI AS ACCE
JOIN SITM.SBEQ_EQUI AS EQUI ON ACCE.ID_EQUI = EQUI.ID_EQUI
JOIN SITM.SFVH_VEHI AS VEHI ON VEHI.ID_VEHI = EQUI.ID_VEHI
JOIN SITM.SFVH_TIPO_VEHI AS TIPO_VEHI ON VEHI.ID_TIPO_VEHI = TIPO_VEHI.ID_TIPO_VEHI
JOIN SITM.COAC_SCRE AS SCRE ON UPPER(SCRE.COD_SCRE) = UPPER(ACCE.TCRE)
WHERE DATE(FCH_ACCE_SALI) BETWEEN DATE('{paramFchIni}') AND (DATE('{paramFchIni}') + 6)
AND ACCE.ID_TIPO_ACCE IN (902,904)
)
GROUP BY FECHA
ORDER BY FECHA