SELECT FECHA, SUM(VALIDACIONES), SUM(COSTOS)
FROM (
SELECT
    DATE(FCH_ACCE_SALI) AS FECHA,
    VEHI.NO_ECON,
    TIPO_VEHI.MOD_COME AS TIPO_VEHICULO,
    COUNT(ID_ACCE_SALI) AS VALIDACIONES,
    SUM(sald_ini) AS COSTOS
FROM SITM.SBOP_ACCE_SALI AS ACCE
JOIN SITM.SBEQ_EQUI AS EQUI ON ACCE.ID_EQUI = EQUI.ID_EQUI
JOIN SITM.CCTM_INV AS INV ON INV.ID_INV=EQUI.ID_INV
JOIN SITM.SBOP_ASGN_TURN AS ASGN ON ASGN.ID_TURN = ACCE.ID_TURN AND ASGN.ID_EQUI=ACCE.ID_EQUI
JOIN SITM.SFVH_VEHI AS VEHI ON VEHI.ID_VEHI = ASGN.ID_VEHI
JOIN SITM.SFVH_TIPO_VEHI AS TIPO_VEHI ON VEHI.ID_TIPO_VEHI = TIPO_VEHI.ID_TIPO_VEHI
WHERE DATE(FCH_ACCE_SALI) BETWEEN DATE('{paramFchIni}') AND (DATE('{paramFchIni}') + 6)
AND ACCE.ID_TIPO_ACCE IN (902,904) AND INV.ID_PROD=56
GROUP BY FECHA,VEHI.NO_ECON, TIPO_VEHICULO
)
GROUP BY FECHA
ORDER BY FECHA