SELECT FECHA,
	COUNT(CASE WHEN SALD_INI=0 AND COST_VIAJ=7 THEN SALD_TARJ END) VAL_CRED_7,
	SUM(CASE WHEN SALD_INI=0 AND COST_VIAJ=7 THEN SALD_TARJ END) COSTOS_CRED_7,
	COUNT(CASE WHEN SALD_INI=0 AND COST_VIAJ=10 THEN SALD_TARJ END) VAL_CRED_10,
	SUM(CASE WHEN SALD_INI=0 AND COST_VIAJ=10 THEN SALD_TARJ END) COSTOS_CRED_10,
	COUNT(CASE WHEN SALD_INI<>0 AND COST_VIAJ=10 THEN SALD_TARJ END) VAL_PAR_CRED_10,
	SUM(CASE WHEN SALD_INI<>0 AND COST_VIAJ=10 THEN SALD_TARJ END) COSTOS_PAR_CRED_10,
	COUNT(CASE WHEN SALD_INI<>0 AND COST_VIAJ=7 THEN SALD_TARJ END) VAL_PAR_CRED_7,
	SUM(CASE WHEN SALD_INI<>0 AND COST_VIAJ=7 THEN SALD_TARJ END) COSTOS_PAR_CRED_7,
	COUNT(CASE WHEN COST_VIAJ=3 THEN SALD_TARJ END) VAL_CRED_3,
	SUM(CASE WHEN COST_VIAJ=3 THEN SALD_TARJ END) COSTOS_CRED_3
FROM (
SELECT
    DATE(FCH_ACCE_SALI) AS FECHA,
    SALD_INI,
    coalesce(COST_VIAJ, 0) AS COST_VIAJ,
    coalesce(SALD_TARJ*-1,0) AS SALD_TARJ
FROM SITM.SBOP_ACCE_SALI AS ACCE
JOIN SITM.SBEQ_EQUI AS EQUI ON ACCE.ID_EQUI = EQUI.ID_EQUI
JOIN SITM.CCTM_INV AS INV ON INV.ID_INV=EQUI.ID_INV
JOIN SITM.SBOP_ASGN_TURN AS ASGN ON ASGN.ID_TURN = ACCE.ID_TURN AND ASGN.ID_EQUI=ACCE.ID_EQUI
JOIN SITM.SFVH_VEHI AS VEHI ON VEHI.ID_VEHI = ASGN.ID_VEHI
JOIN SITM.SFVH_TIPO_VEHI AS TIPO_VEHI ON VEHI.ID_TIPO_VEHI = TIPO_VEHI.ID_TIPO_VEHI
WHERE DATE(FCH_ACCE_SALI) BETWEEN DATE('{paramFchIni}') AND (DATE('{paramFchIni}') + 6)
AND ACCE.ID_TIPO_ACCE IN (902,904) AND INV.ID_PROD=56
)
GROUP BY FECHA
ORDER BY FECHA