SELECT FECHA, 
	SUM(CASE WHEN CREDENCIAL LIKE 'MONEDERO%' AND COSTO=0 THEN VALIDACIONES ELSE 0 END) MONEDERO_COSTO_0,
	SUM(CASE WHEN CREDENCIAL LIKE 'MONEDERO%' AND COSTO=3 THEN VALIDACIONES ELSE 0 END) MONEDERO_COSTO_3,
	SUM(CASE WHEN CREDENCIAL LIKE 'MONEDERO%' AND COSTO=10 THEN VALIDACIONES ELSE 0 END) MONEDERO_COSTO_10,
	SUM(CASE WHEN CREDENCIAL LIKE '%SERVICIOS%' THEN VALIDACIONES ELSE 0 END) SERVICIO_SAB,
	SUM(CASE WHEN CREDENCIAL LIKE '%ADMINISTRADOR%' THEN VALIDACIONES ELSE 0 END) SUPERVISOR
FROM (
SELECT
DATE(FCH_ACCE_SALI) AS FECHA, 
SCRE.DES_SCRE AS CREDENCIAL,
COST_VIAJ AS COSTO,
COUNT(ID_ACCE_SALI) AS VALIDACIONES,
SUM(COST_VIAJ) AS COSTOS
FROM SITM.SBOP_ACCE_SALI AS ACCE
JOIN SITM.SBEQ_EQUI AS EQUI ON ACCE.ID_EQUI = EQUI.ID_EQUI AND EQUI.ID_LIN_EST IS NOT NULL
JOIN SITM.COAC_SCRE AS SCRE ON UPPER(SCRE.COD_SCRE) = UPPER(ACCE.TCRE)
WHERE DATE(FCH_ACCE_SALI) BETWEEN DATE('{paramFchIni}') AND (DATE('{paramFchIni}') + 6)
AND ACCE.ID_TIPO_ACCE NOT IN (327,868)
GROUP BY FECHA, CREDENCIAL, COSTO
ORDER BY FECHA ASC, CREDENCIAL ASC, COSTO ASC
)
GROUP BY FECHA
ORDER BY FECHA