SELECT FECHA, SUM(CASE WHEN CREDENCIAL LIKE '%PREFERENCIAL%' THEN VALIDACIONES ELSE 0 END) MANTENIMIENTO
FROM (
SELECT
DATE(FCH_ACCE_SALI) AS FECHA, 
SCRE.DES_SCRE AS CREDENCIAL,
COST_VIAJ AS COSTO,
COUNT(ID_ACCE_SALI) AS VALIDACIONES,
SUM(COST_VIAJ) AS COSTOS
FROM SITM.SBOP_ACCE_SALI AS ACCE
JOIN SITM.SBEQ_EQUI AS EQUI ON ACCE.ID_EQUI = EQUI.ID_EQUI AND EQUI.ID_LIN_EST IS NOT NULL
JOIN SITM.COAC_SCRE AS SCRE ON UPPER(SCRE.COD_SCRE) = UPPER(ACCE.TCRE)
WHERE DATE(FCH_ACCE_SALI) BETWEEN DATE('{paramFchIni}') AND (DATE('{paramFchIni}') + 6)
AND ACCE.ID_TIPO_ACCE NOT IN (327,868)
GROUP BY FECHA, CREDENCIAL, COSTO
ORDER BY FECHA ASC, CREDENCIAL ASC, COSTO ASC
)
GROUP BY FECHA
ORDER BY FECHA