SELECT FECHA, SUM(RECARGAS), SUM(MONTO)
FROM (
SELECT
DATE(TRAN.FCH_TRAN) AS FECHA,
EQUI.id_equi,
COUNT(TRAN.ID_TRAN) AS RECARGAS,
    CASE
        WHEN UPPER(TRAN.TIPO_TRAN) = 'V' AND TRAN.IMPO_TRAN > 10 THEN SUM(TRAN.IMPO_TRAN - 10)
        WHEN UPPER(TRAN.TIPO_TRAN) IN ('C','K') THEN SUM(TRAN.Sald_ini*-1)
        ELSE SUM(TRAN.IMPO_TRAN)
    END AS MONTO
FROM SITM.SBOP_TRAN AS TRAN
JOIN SITM.SBEQ_EQUI AS EQUI ON TRAN.ID_EQUI = EQUI.ID_EQUI
JOIN SITM.CCTM_INV AS INV ON EQUI.ID_INV = INV.ID_INV
JOIN SITM.CCTM_PROD AS PROD ON INV.ID_PROD = PROD.ID_PROD
WHERE DATE(TRAN.FCH_TRAN) BETWEEN DATE('{paramFchIni}') AND (DATE('{paramFchIni}') + 6)
and TRAN.id_equi in (471,472)
AND UPPER(TRAN.TIPO_TRAN) IN ('K','C')
GROUP BY FECHA, EQUI.id_equi, TIPO_TRAN, IMPO_TRAN
)
GROUP BY FECHA
ORDER BY FECHA