SELECT FECHA,
	SUM(CASE WHEN EQUIPO LIKE 'KIOSKO%' THEN VENTAS ELSE 0 END) VENTAS_KVR,
	SUM(CASE WHEN EQUIPO LIKE 'KIOSKO%' THEN MONTO ELSE 0 END) MONTO_KVR,
	SUM(CASE WHEN EQUIPO LIKE 'GESTOR%' THEN VENTAS ELSE 0 END) VENTAS_GESTOR,
	SUM(CASE WHEN EQUIPO LIKE 'GESTOR%' THEN MONTO ELSE 0 END) MONTO_GESTOR
FROM (
SELECT 
    DATE(TRAN.FCH_TRAN) AS FECHA,
    PROD.DES_PROD AS EQUIPO,
    COUNT(TRAN.ID_TRAN) AS VENTAS,
    (COUNT(TRAN.ID_TRAN) * 10) AS MONTO
FROM SITM.SBOP_TRAN AS TRAN
JOIN SITM.SBEQ_EQUI AS EQUI ON TRAN.ID_EQUI = EQUI.ID_EQUI
JOIN SITM.CCTM_INV AS INV ON EQUI.ID_INV = INV.ID_INV
JOIN SITM.CCTM_PROD AS PROD ON INV.ID_PROD = PROD.ID_PROD
WHERE DATE(TRAN.FCH_TRAN) BETWEEN DATE('{paramFchIni}') AND (DATE('{paramFchIni}') + 6)
AND UPPER(TRAN.TIPO_TRAN) = 'V'
GROUP BY FECHA, EQUIPO 
)
GROUP BY FECHA
ORDER BY FECHA